const kurlyDB = [
    {
        src:'./image/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./image/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },
    {
        src: './image/kurly_003.jpg',
        name: '[매일유업] 바리스타룰스 아메리카노 330ml',
        summary: '깔끔한 맛의 커피 음료',
        price: 1800,
        sale: 10,
        review: 47,
    },
    {
        src: './image/kurly_004.jpg',
        name: '[오뚜기] 진짬뽕 멀티팩 (4개입)',
        summary: '얼큰하고 진한 국물맛',
        price: 4480,
        sale: 15,
        review: 233,
    },
    {
        src: './image/kurly_005.jpg',
        name: '[풀무원] 얇은피 꽉찬속 김치만두',
        summary: '바삭한 얇은피와 매콤한 김치 속',
        price: 4980,
        sale: 12,
        review: 98,
    },
    {
        src: './image/kurly_006.jpg',
        name: '[CJ] 고메 함박스테이크 2입',
        summary: '두툼한 패티와 부드러운 그레이비',
        price: 5980,
        sale: 8,
        review: 65,
    },
    {
        src: './image/kurly_007.jpg',
        name: '[동원] 리챔 오리지널 200g',
        summary: '짭짤한 고소함 그대로',
        price: 3280,
        sale: 5,
        review: 142,
    },
    {
        src: './image/kurly_008.jpg',
        name: '[서울우유] 나100% 우유 900ml',
        summary: '신선한 국내산 1A등급 원유',
        price: 2450,
        sale: 7,
        review: 91,
    },
    {
        src: './image/kurly_009.jpg',
        name: '[청정원] 햇살담은 간장 진한맛 500ml',
        summary: '요리에 감칠맛을 더하는 필수 아이템',
        price: 1980,
        sale: 6,
        review: 34,
    },
    {
        src: './image/kurly_010.jpg',
        name: '[빙그레] 바나나맛 우유 240ml',
        summary: '부드럽고 달콤한 국민음료',
        price: 1500,
        sale: 3,
        review: 219,
    },
    {
        src: './image/kurly_011.jpg',
        name: '[오리온] 촉촉한 초코칩 12개입',
        summary: '촉촉하고 달콤한 간식',
        price: 2980,
        sale: 10,
        review: 74,
    },
    {
        src: './image/kurly_img12.jpg',
        name: '[농심] 새우깡 90g',
        summary: '언제 먹어도 맛있는 국민과자',
        price: 1380,
        sale: 5,
        review: 301,
    }
    
]